/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWatchRouteImport } from './routes/_app/watch'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReelsRouteImport } from './routes/_app/reels'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPagesRouteImport } from './routes/_app/pages'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppGroupsRouteImport } from './routes/_app/groups'
import { Route as AppFriendsRouteImport } from './routes/_app/friends'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppProfileUserIdRouteImport } from './routes/_app/profile.$userId'
import { Route as AppPagesPageIdRouteImport } from './routes/_app/pages.$pageId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWatchRoute = AppWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReelsRoute = AppReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPagesRoute = AppPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUserIdRoute = AppProfileUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppPagesPageIdRoute = AppPagesPageIdRouteImport.update({
  id: '/$pageId',
  path: '/$pageId',
  getParentRoute: () => AppPagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/friends': typeof AppFriendsRoute
  '/groups': typeof AppGroupsRoute
  '/home': typeof AppHomeRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pages': typeof AppPagesRouteWithChildren
  '/profile': typeof AppProfileRouteWithChildren
  '/reels': typeof AppReelsRoute
  '/settings': typeof AppSettingsRoute
  '/watch': typeof AppWatchRoute
  '/pages/$pageId': typeof AppPagesPageIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AppAdminRoute
  '/friends': typeof AppFriendsRoute
  '/groups': typeof AppGroupsRoute
  '/home': typeof AppHomeRoute
  '/messages': typeof AppMessagesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pages': typeof AppPagesRouteWithChildren
  '/profile': typeof AppProfileRouteWithChildren
  '/reels': typeof AppReelsRoute
  '/settings': typeof AppSettingsRoute
  '/watch': typeof AppWatchRoute
  '/pages/$pageId': typeof AppPagesPageIdRoute
  '/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/register': typeof RegisterRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/groups': typeof AppGroupsRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pages': typeof AppPagesRouteWithChildren
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/reels': typeof AppReelsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/watch': typeof AppWatchRoute
  '/_app/pages/$pageId': typeof AppPagesPageIdRoute
  '/_app/profile/$userId': typeof AppProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/admin'
    | '/friends'
    | '/groups'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/pages'
    | '/profile'
    | '/reels'
    | '/settings'
    | '/watch'
    | '/pages/$pageId'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/admin'
    | '/friends'
    | '/groups'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/pages'
    | '/profile'
    | '/reels'
    | '/settings'
    | '/watch'
    | '/pages/$pageId'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/register'
    | '/_app/admin'
    | '/_app/friends'
    | '/_app/groups'
    | '/_app/home'
    | '/_app/messages'
    | '/_app/notifications'
    | '/_app/pages'
    | '/_app/profile'
    | '/_app/reels'
    | '/_app/settings'
    | '/_app/watch'
    | '/_app/pages/$pageId'
    | '/_app/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/watch': {
      id: '/_app/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof AppWatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reels': {
      id: '/_app/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof AppReelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pages': {
      id: '/_app/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof AppPagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$userId': {
      id: '/_app/profile/$userId'
      path: '/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof AppProfileUserIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/pages/$pageId': {
      id: '/_app/pages/$pageId'
      path: '/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof AppPagesPageIdRouteImport
      parentRoute: typeof AppPagesRoute
    }
  }
}

interface AppPagesRouteChildren {
  AppPagesPageIdRoute: typeof AppPagesPageIdRoute
}

const AppPagesRouteChildren: AppPagesRouteChildren = {
  AppPagesPageIdRoute: AppPagesPageIdRoute,
}

const AppPagesRouteWithChildren = AppPagesRoute._addFileChildren(
  AppPagesRouteChildren,
)

interface AppProfileRouteChildren {
  AppProfileUserIdRoute: typeof AppProfileUserIdRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileUserIdRoute: AppProfileUserIdRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppGroupsRoute: typeof AppGroupsRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPagesRoute: typeof AppPagesRouteWithChildren
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppReelsRoute: typeof AppReelsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWatchRoute: typeof AppWatchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppGroupsRoute: AppGroupsRoute,
  AppHomeRoute: AppHomeRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPagesRoute: AppPagesRouteWithChildren,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppReelsRoute: AppReelsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWatchRoute: AppWatchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
